{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
appVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "contoso-app.fullname" . }}-actuator
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels: {{- include "contoso-app.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.metrics.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels: {{- include "contoso-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: actuatorhttp
      path: /actuator/prometheus
      {{- if .Values.metrics.serviceMonitor.interval }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}